const express = require('express');
const { createPlaylist } = require('../services/spotify');

const router = express.Router();

router.post('/', async (req, res) => {
  const { songs, prompt } = req.body;
  if (!Array.isArray(songs) || songs.length === 0) {
    return res.status(400).json({ error: 'songs array is required' });
  }

  try {
    const name = `Music Map: ${prompt || 'My Playlist'}`;
    const description = `Generated by Music Map for: "${prompt}"`;
    const url = await createPlaylist(name, description, songs);
    res.json({ url });
  } catch (err) {
    console.error('playlist error:', err.message);
    res.status(500).json({ error: 'Failed to create playlist' });
  }
});

module.exports = router;
