const express = require('express');
const { getMusicProvider } = require('../providers/music');

const router = express.Router();

router.post('/', async (req, res) => {
  const { songs, prompt, provider } = req.body;
  if (!Array.isArray(songs) || songs.length === 0) {
    return res.status(400).json({ error: 'songs array is required' });
  }

  try {
    const label = (prompt || 'My Playlist').trim();
    const name = `Music Map: ${label}`;
    const description = `Generated by Music Map for: "${label}"`;
    const { playlistUrl, tracks } = await getMusicProvider(provider).createPlaylist(name, description, songs);
    res.json({ url: playlistUrl, tracks });
  } catch (err) {
    const spotifyError = err.response?.data;
    console.error('playlist error:', err.message, spotifyError ? JSON.stringify(spotifyError) : '');
    res.status(500).json({ error: 'Failed to create playlist' });
  }
});

module.exports = router;
